### ISSUE TITLE
Undefined variable

### ISSUE THREAD

**Issue by eelsirhc** [AeolisResearch/divergence_damping#1]
The `Pt` variable is undefined on line 389. There is a `PT` variable defined earlier, not sure if that's the one you want.

https://github.com/AeolisResearch/divergence_damping/blob/b871dcfc9482fb76f08689af691de4119dc6528c/solve_tidal_eqs.py#L385-L389

(Also, the example says `solve_tide_v` returns two values when it returns 3, and the `lbc` input value is missing in the example).

**Comment by yuan2lian2** [comment]
Pt was not used unless pf=0. This is why I didn't notice the typo. I just updated the code to the latest version to address the issues you mentioned.
